<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
    <ProjectReference Include="..\..\samples\Croniq.Sample.Jobs\Croniq.Sample.Jobs.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Core\Croniq.Core.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Persistence.SqlServer\Croniq.Persistence.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Croniq.JobStore.InMemory\Croniq.JobStore.InMemory.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Providers.Default\Croniq.Providers.Default.csproj" />
  </ItemGroup>
</Project>
