server:
  http_listen_port: 3200
  grpc_listen_port: 3201

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
    wal:
      path: /tmp/tempo/wal
