// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Auth;

/// <summary>
/// Represents the contract for the stored procedure <c>auth.ApiClientGet</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class ApiClientGetRequest
{
    public int? TenantId { get; init; }
    public int? ClientId { get; init; }
}

public readonly record struct ApiClientGetInput(
    int? TenantId,
    int? ClientId
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>auth.ResultSet1</c>.
/// </summary>
public readonly record struct ApiClientGetResultSet1Result(
    int ClientId,
    int TenantId,
    string? Name,
    string? Environment,
    string? Scopes,
    bool IsDeleted
);

public sealed class ApiClientGetResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public IReadOnlyList<ApiClientGetResultSet1Result> Result { get; init; } = Array.Empty<ApiClientGetResultSet1Result>();
}
internal static class ApiClientGetRequestMapper
{
    public static async ValueTask<ApiClientGetInput> ToInputAsync(ApiClientGetRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new ApiClientGetRequest();
        int? TenantId = request.TenantId;
        if (!HasValue(TenantId))
        {
	    TenantId = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiClientGet]", "@TenantId", false, TenantId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(TenantId))
        {
            throw new InvalidOperationException("Parameter @TenantId must be supplied by the request or a configured binding.");
        }
        int? ClientId = request.ClientId;
        if (!HasValue(ClientId))
        {
	    ClientId = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiClientGet]", "@ClientId", false, ClientId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(ClientId))
        {
            throw new InvalidOperationException("Parameter @ClientId must be supplied by the request or a configured binding.");
        }

        return new ApiClientGetInput(
            TenantId,
            ClientId
        );
    }

    public static ValueTask<ApiClientGetInput> ToInputAsync(ApiClientGetRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class ApiClientGetPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@TenantId", System.Data.DbType.Int32, 4, false, true),
            new("@ClientId", System.Data.DbType.Int32, 4, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>(); int o0=ReaderUtil.TryGetOrdinal(r, "ClientId"); int o1=ReaderUtil.TryGetOrdinal(r, "TenantId"); int o2=ReaderUtil.TryGetOrdinal(r, "Name"); int o3=ReaderUtil.TryGetOrdinal(r, "Environment"); int o4=ReaderUtil.TryGetOrdinal(r, "Scopes"); int o5=ReaderUtil.TryGetOrdinal(r, "IsDeleted"); while (await r.ReadAsync(ct).ConfigureAwait(false)) { list.Add(new ApiClientGetResultSet1Result(o0 < 0 ? default(int) : r.GetInt32(o0), o1 < 0 ? default(int) : r.GetInt32(o1), o2 < 0 ? null : (r.IsDBNull(o2) ? null : r.GetString(o2)), o3 < 0 ? null : (r.IsDBNull(o3) ? null : r.GetString(o3)), o4 < 0 ? null : (r.IsDBNull(o4) ? null : r.GetString(o4)), o5 < 0 ? default(bool) : r.GetBoolean(o5))); } return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new ApiClientGetResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 ? Array.ConvertAll(rows0, o => (ApiClientGetResultSet1Result)o).ToList() : (rs.Length > 0 && rs[0] is System.Collections.Generic.List<object> list0 ? Array.ConvertAll(list0.ToArray(), o => (ApiClientGetResultSet1Result)o).ToList() : Array.Empty<ApiClientGetResultSet1Result>())
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (ApiClientGetInput)state!;
			cmd.Parameters["@TenantId"].Value = (object?)input.TenantId ?? DBNull.Value;
			cmd.Parameters["@ClientId"].Value = (object?)input.ClientId ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[auth].[ApiClientGet]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[auth].[ApiClientGet]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class ApiClientGetExtensions
{
	public static async Task<ApiClientGetResult> ApiClientGetAsync(this IXtraqDbContext db, ApiClientGetRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ApiClientGetRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await ApiClientGetAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<ApiClientGetResult> ApiClientGetAsync(this IXtraqDbContext db, ApiClientGetInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await ApiClientGetProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

	/// <summary>Streams result set <c>ResultSet1</c> without buffering it into the aggregate payload.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		await using var connection = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		await ApiClientGetProcedure.StreamResultResultSet1Async(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, connection, input, onRowAsync, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static async Task StreamResultResultSet1Async(this IXtraqDbContext db, ApiClientGetRequest request, Func<ApiClientGetResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(db);
		ArgumentNullException.ThrowIfNull(onRowAsync);
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ApiClientGetRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		await StreamResultResultSet1Async(db, input, onRowAsync, cancellationToken).ConfigureAwait(false);
		return;
	}

	/// <summary>Streams result set <c>ResultSet1</c> using a request DTO; request is mapped and hydrated before streaming.</summary>
	public static Task StreamResultResultSet1Async(this IXtraqDbContext db, ApiClientGetRequest request, Func<ApiClientGetResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(db, request, (row, ct) => onRowAsync(row), cancellationToken);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class ApiClientGetProcedure
{
	public const string Name = "[auth].[ApiClientGet]";
	public static Task<ApiClientGetResult> ExecuteAsync(DbConnection connection, ApiClientGetInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<ApiClientGetResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ApiClientGetInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<ApiClientGetResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ApiClientGetInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<ApiClientGetResult>(interceptorProvider, bindingProvider, connection, ApiClientGetPlan.Instance, input, cancellationToken);
	}

	/// <summary>Streams result set <c>ResultSet1</c> using the supplied row callback.</summary>
	public static Task StreamResultResultSet1Async(DbConnection connection, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(null, null, connection, input, onRowAsync, cancellationToken);

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
		=> StreamResultResultSet1Async(interceptorProvider, null, connection, input, onRowAsync, cancellationToken);

	public static async Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, CancellationToken, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(connection);
		ArgumentNullException.ThrowIfNull(onRowAsync);

		async Task StreamCoreAsync(DbDataReader reader, CancellationToken ct)
		{
            int o0=ReaderUtil.TryGetOrdinal(reader, "ClientId");
            int o1=ReaderUtil.TryGetOrdinal(reader, "TenantId");
            int o2=ReaderUtil.TryGetOrdinal(reader, "Name");
            int o3=ReaderUtil.TryGetOrdinal(reader, "Environment");
            int o4=ReaderUtil.TryGetOrdinal(reader, "Scopes");
            int o5=ReaderUtil.TryGetOrdinal(reader, "IsDeleted");
			while (await reader.ReadAsync(ct).ConfigureAwait(false))
			{
				var row = new ApiClientGetResultSet1Result(o0 < 0 ? default(int) : reader.GetInt32(o0), o1 < 0 ? default(int) : reader.GetInt32(o1), o2 < 0 ? null : (reader.IsDBNull(o2) ? null : reader.GetString(o2)), o3 < 0 ? null : (reader.IsDBNull(o3) ? null : reader.GetString(o3)), o4 < 0 ? null : (reader.IsDBNull(o4) ? null : reader.GetString(o4)), o5 < 0 ? default(bool) : reader.GetBoolean(o5));
				await onRowAsync(row, ct).ConfigureAwait(false);
			}
		}

		await ProcedureExecutor.StreamResultSetAsync(interceptorProvider, bindingProvider, connection, ApiClientGetPlan.Instance, 0, StreamCoreAsync, input, cancellationToken).ConfigureAwait(false);
	}

	public static Task StreamResultResultSet1Async(DbConnection connection, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(null, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

	public static Task StreamResultResultSet1Async(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ApiClientGetInput input, Func<ApiClientGetResultSet1Result, ValueTask> onRowAsync, CancellationToken cancellationToken = default)
	{
		ArgumentNullException.ThrowIfNull(onRowAsync);
		return StreamResultResultSet1Async(interceptorProvider, null, connection, input, (row, ct) => onRowAsync(row), cancellationToken);
	}

}
