// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Auth;

/// <summary>
/// Represents the contract for the stored procedure <c>auth.ApiKeyIssue</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class ApiKeyIssueRequest
{
    public int? TenantId { get; init; }
    public int? ClientId { get; init; }
    [System.ComponentModel.DataAnnotations.StringLength(32)]
    public string? Environment { get; init; }
    public string? Scopes { get; init; }
    public int? TtlMinutes { get; init; }
    [System.ComponentModel.DataAnnotations.StringLength(128)]
    public string? CreatedBy { get; init; }
}

public readonly record struct ApiKeyIssueInput(
    int? TenantId,
    int? ClientId,
    string? Environment,
    string? Scopes,
    int? TtlMinutes,
    string? CreatedBy
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>auth.ApiKeyIssue</c>.
/// </summary>
public readonly record struct ApiKeyIssueOutput(
    int? KeyId,
    string? KeyRef,
    string? PlaintextKey,
    string? SecretPreview,
    DateTime? ExpiresUtc
);

public sealed class ApiKeyIssueResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public ApiKeyIssueOutput? Output { get; init; }
}
internal static class ApiKeyIssueRequestMapper
{
    public static async ValueTask<ApiKeyIssueInput> ToInputAsync(ApiKeyIssueRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new ApiKeyIssueRequest();
        int? TenantId = request.TenantId;
        if (!HasValue(TenantId))
        {
	    TenantId = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiKeyIssue]", "@TenantId", false, TenantId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(TenantId))
        {
            throw new InvalidOperationException("Parameter @TenantId must be supplied by the request or a configured binding.");
        }
        int? ClientId = request.ClientId;
        if (!HasValue(ClientId))
        {
	    ClientId = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiKeyIssue]", "@ClientId", false, ClientId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(ClientId))
        {
            throw new InvalidOperationException("Parameter @ClientId must be supplied by the request or a configured binding.");
        }
        string? Environment = request.Environment;
        if (!HasValue(Environment))
        {
	    Environment = await ResolveAsync<string?>(bindingProvider, "[auth].[ApiKeyIssue]", "@Environment", false, Environment, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Environment))
        {
            throw new InvalidOperationException("Parameter @Environment must be supplied by the request or a configured binding.");
        }
        string? Scopes = request.Scopes;
        if (!HasValue(Scopes))
        {
	    Scopes = await ResolveAsync<string?>(bindingProvider, "[auth].[ApiKeyIssue]", "@Scopes", false, Scopes, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Scopes))
        {
            throw new InvalidOperationException("Parameter @Scopes must be supplied by the request or a configured binding.");
        }
        int? TtlMinutes = request.TtlMinutes;
        if (!HasValue(TtlMinutes))
        {
	    TtlMinutes = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiKeyIssue]", "@TtlMinutes", false, TtlMinutes, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(TtlMinutes))
        {
            throw new InvalidOperationException("Parameter @TtlMinutes must be supplied by the request or a configured binding.");
        }
        string? CreatedBy = request.CreatedBy;
        if (!HasValue(CreatedBy))
        {
	    CreatedBy = await ResolveAsync<string?>(bindingProvider, "[auth].[ApiKeyIssue]", "@CreatedBy", false, CreatedBy, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(CreatedBy))
        {
            throw new InvalidOperationException("Parameter @CreatedBy must be supplied by the request or a configured binding.");
        }

        return new ApiKeyIssueInput(
            TenantId,
            ClientId,
            Environment,
            Scopes,
            TtlMinutes,
            CreatedBy
        );
    }

    public static ValueTask<ApiKeyIssueInput> ToInputAsync(ApiKeyIssueRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class ApiKeyIssuePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@TenantId", System.Data.DbType.Int32, 4, false, true),
            new("@ClientId", System.Data.DbType.Int32, 4, false, true),
            new("@Environment", System.Data.DbType.String, 32, false, true),
            new("@Scopes", System.Data.DbType.String, null, false, true),
            new("@TtlMinutes", System.Data.DbType.Int32, 4, false, true),
            new("@CreatedBy", System.Data.DbType.String, 128, false, true),
            new("@KeyId", System.Data.DbType.Int32, 4, true, true),
            new("@KeyRef", System.Data.DbType.String, 64, true, true),
            new("@PlaintextKey", System.Data.DbType.String, 512, true, true),
            new("@SecretPreview", System.Data.DbType.String, 16, true, true),
            new("@ExpiresUtc", System.Data.DbType.DateTime2, 7, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new ApiKeyIssueOutput(values.TryGetValue("KeyId", out var v_KeyId) ? (int?)v_KeyId : default, values.TryGetValue("KeyRef", out var v_KeyRef) ? (string?)v_KeyRef : default, values.TryGetValue("PlaintextKey", out var v_PlaintextKey) ? (string?)v_PlaintextKey : default, values.TryGetValue("SecretPreview", out var v_SecretPreview) ? (string?)v_SecretPreview : default, values.TryGetValue("ExpiresUtc", out var v_ExpiresUtc) ? (DateTime?)v_ExpiresUtc : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new ApiKeyIssueResult
			{
				Success = success,
				Error = error,
				Output = (ApiKeyIssueOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (ApiKeyIssueInput)state!;
			cmd.Parameters["@TenantId"].Value = (object?)input.TenantId ?? DBNull.Value;
			cmd.Parameters["@ClientId"].Value = (object?)input.ClientId ?? DBNull.Value;
			cmd.Parameters["@Environment"].Value = (object?)input.Environment ?? DBNull.Value;
			cmd.Parameters["@Scopes"].Value = (object?)input.Scopes ?? DBNull.Value;
			cmd.Parameters["@TtlMinutes"].Value = (object?)input.TtlMinutes ?? DBNull.Value;
			cmd.Parameters["@CreatedBy"].Value = (object?)input.CreatedBy ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[auth].[ApiKeyIssue]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[auth].[ApiKeyIssue]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class ApiKeyIssueExtensions
{
	public static async Task<ApiKeyIssueResult> ApiKeyIssueAsync(this IXtraqDbContext db, ApiKeyIssueRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ApiKeyIssueRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await ApiKeyIssueAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<ApiKeyIssueResult> ApiKeyIssueAsync(this IXtraqDbContext db, ApiKeyIssueInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await ApiKeyIssueProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class ApiKeyIssueProcedure
{
	public const string Name = "[auth].[ApiKeyIssue]";
	public static Task<ApiKeyIssueResult> ExecuteAsync(DbConnection connection, ApiKeyIssueInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<ApiKeyIssueResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ApiKeyIssueInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<ApiKeyIssueResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ApiKeyIssueInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<ApiKeyIssueResult>(interceptorProvider, bindingProvider, connection, ApiKeyIssuePlan.Instance, input, cancellationToken);
	}

}
