// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Auth;

/// <summary>
/// Represents the contract for the stored procedure <c>auth.ApiKeyRotate</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class ApiKeyRotateRequest
{
    public int? TenantId { get; init; }
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string? KeyRef { get; init; }
}

public readonly record struct ApiKeyRotateInput(
    int? TenantId,
    string? KeyRef,
    string? Actor
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>auth.ApiKeyRotate</c>.
/// </summary>
public readonly record struct ApiKeyRotateOutput(
    string? PlaintextKey,
    string? SecretPreview
);

public sealed class ApiKeyRotateResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public ApiKeyRotateOutput? Output { get; init; }
}
internal static class ApiKeyRotateRequestMapper
{
    public static async ValueTask<ApiKeyRotateInput> ToInputAsync(ApiKeyRotateRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new ApiKeyRotateRequest();
        int? TenantId = request.TenantId;
        if (!HasValue(TenantId))
        {
	    TenantId = await ResolveAsync<int?>(bindingProvider, "[auth].[ApiKeyRotate]", "@TenantId", false, TenantId, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(TenantId))
        {
            throw new InvalidOperationException("Parameter @TenantId must be supplied by the request or a configured binding.");
        }
        string? KeyRef = request.KeyRef;
        if (!HasValue(KeyRef))
        {
	    KeyRef = await ResolveAsync<string?>(bindingProvider, "[auth].[ApiKeyRotate]", "@KeyRef", false, KeyRef, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(KeyRef))
        {
            throw new InvalidOperationException("Parameter @KeyRef must be supplied by the request or a configured binding.");
        }
        string? Actor = default;
        if (!HasValue(Actor))
        {
	    Actor = await ResolveAsync<string?>(bindingProvider, "[auth].[ApiKeyRotate]", "@Actor", false, Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }

        return new ApiKeyRotateInput(
            TenantId,
            KeyRef,
            Actor
        );
    }

    public static ValueTask<ApiKeyRotateInput> ToInputAsync(ApiKeyRotateRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class ApiKeyRotatePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@TenantId", System.Data.DbType.Int32, 4, false, true),
            new("@KeyRef", System.Data.DbType.String, 64, false, true),
            new("@Actor", System.Data.DbType.String, 128, false, true),
            new("@PlaintextKey", System.Data.DbType.String, 512, true, true),
            new("@SecretPreview", System.Data.DbType.String, 16, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new ApiKeyRotateOutput(values.TryGetValue("PlaintextKey", out var v_PlaintextKey) ? (string?)v_PlaintextKey : default, values.TryGetValue("SecretPreview", out var v_SecretPreview) ? (string?)v_SecretPreview : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new ApiKeyRotateResult
			{
				Success = success,
				Error = error,
				Output = (ApiKeyRotateOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (ApiKeyRotateInput)state!;
			cmd.Parameters["@TenantId"].Value = (object?)input.TenantId ?? DBNull.Value;
			cmd.Parameters["@KeyRef"].Value = (object?)input.KeyRef ?? DBNull.Value;
			cmd.Parameters["@Actor"].Value = (object?)input.Actor ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[auth].[ApiKeyRotate]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[auth].[ApiKeyRotate]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class ApiKeyRotateExtensions
{
	public static async Task<ApiKeyRotateResult> ApiKeyRotateAsync(this IXtraqDbContext db, ApiKeyRotateRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await ApiKeyRotateRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await ApiKeyRotateAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<ApiKeyRotateResult> ApiKeyRotateAsync(this IXtraqDbContext db, ApiKeyRotateInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await ApiKeyRotateProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class ApiKeyRotateProcedure
{
	public const string Name = "[auth].[ApiKeyRotate]";
	public static Task<ApiKeyRotateResult> ExecuteAsync(DbConnection connection, ApiKeyRotateInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<ApiKeyRotateResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, ApiKeyRotateInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<ApiKeyRotateResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, ApiKeyRotateInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<ApiKeyRotateResult>(interceptorProvider, bindingProvider, connection, ApiKeyRotatePlan.Instance, input, cancellationToken);
	}

}
