// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.GuardTriggerRef</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class GuardTriggerRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<TriggerRef> Trigger { get; init; }
}

public readonly record struct GuardTriggerRefInput(
    IReadOnlyList<TriggerRef> Trigger
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.GuardTriggerRef</c>.
/// </summary>
public readonly record struct GuardTriggerRefOutput(
    string? TriggerKey,
    string? JobKey,
    int? TenantId,
    long? JobId,
    string? Environment,
    string? Namespace,
    string? Name,
    string? Variant,
    string? CronExpression,
    string? TimeZoneId,
    DateTime? StartAtUtc,
    DateTime? EndAtUtc,
    bool? Enabled,
    string? Metadata
);

public sealed class GuardTriggerRefResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public GuardTriggerRefOutput? Output { get; init; }
}

internal static class GuardTriggerRefRequestMapper
{
    public static async ValueTask<GuardTriggerRefInput> ToInputAsync(GuardTriggerRefRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new GuardTriggerRefRequest();
        IReadOnlyList<TriggerRef>? Trigger = request.Trigger;
        if (!HasValue(Trigger))
        {
            Trigger = await ResolveTableAsync<TriggerRef>(bindingProvider, "[croniq].[GuardTriggerRef]", "@Trigger", Trigger, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Trigger))
        {
            throw new InvalidOperationException("Parameter @Trigger must be supplied by the request or a configured binding.");
        }

        return new GuardTriggerRefInput(
            Trigger!
        );
    }

    public static ValueTask<GuardTriggerRefInput> ToInputAsync(GuardTriggerRefRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class GuardTriggerRefPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Trigger", System.Data.DbType.Object, null, false, false, "croniq.TriggerRef"),
            new("@TriggerKey", System.Data.DbType.String, 64, true, true),
            new("@JobKey", System.Data.DbType.String, 64, true, true),
            new("@TenantId", System.Data.DbType.Int32, 4, true, true),
            new("@JobId", System.Data.DbType.Int64, 8, true, true),
            new("@Environment", System.Data.DbType.String, 32, true, true),
            new("@Namespace", System.Data.DbType.String, 64, true, true),
            new("@Name", System.Data.DbType.String, 128, true, true),
            new("@Variant", System.Data.DbType.String, 64, true, true),
            new("@CronExpression", System.Data.DbType.String, 256, true, true),
            new("@TimeZoneId", System.Data.DbType.String, 64, true, true),
            new("@StartAtUtc", System.Data.DbType.DateTime2, 7, true, true),
            new("@EndAtUtc", System.Data.DbType.DateTime2, 7, true, true),
            new("@Enabled", System.Data.DbType.Boolean, 1, true, true),
            new("@Metadata", System.Data.DbType.String, null, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new GuardTriggerRefOutput(values.TryGetValue("TriggerKey", out var v_TriggerKey) ? (string?)v_TriggerKey : default, values.TryGetValue("JobKey", out var v_JobKey) ? (string?)v_JobKey : default, values.TryGetValue("TenantId", out var v_TenantId) ? (int?)v_TenantId : default, values.TryGetValue("JobId", out var v_JobId) ? (long?)v_JobId : default, values.TryGetValue("Environment", out var v_Environment) ? (string?)v_Environment : default, values.TryGetValue("Namespace", out var v_Namespace) ? (string?)v_Namespace : default, values.TryGetValue("Name", out var v_Name) ? (string?)v_Name : default, values.TryGetValue("Variant", out var v_Variant) ? (string?)v_Variant : default, values.TryGetValue("CronExpression", out var v_CronExpression) ? (string?)v_CronExpression : default, values.TryGetValue("TimeZoneId", out var v_TimeZoneId) ? (string?)v_TimeZoneId : default, values.TryGetValue("StartAtUtc", out var v_StartAtUtc) ? (DateTime?)v_StartAtUtc : default, values.TryGetValue("EndAtUtc", out var v_EndAtUtc) ? (DateTime?)v_EndAtUtc : default, values.TryGetValue("Enabled", out var v_Enabled) ? (bool?)v_Enabled : default, values.TryGetValue("Metadata", out var v_Metadata) ? (string?)v_Metadata : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new GuardTriggerRefResult
			{
				Success = success,
				Error = error,
				Output = (GuardTriggerRefOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (GuardTriggerRefInput)state!;
			{ var prm = cmd.Parameters["@Trigger"]; var source = input.Trigger; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.TriggerRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[GuardTriggerRef]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[GuardTriggerRef]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class GuardTriggerRefExtensions
{
	public static async Task<GuardTriggerRefResult> GuardTriggerRefAsync(this IXtraqDbContext db, GuardTriggerRefRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await GuardTriggerRefRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await GuardTriggerRefAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<GuardTriggerRefResult> GuardTriggerRefAsync(this IXtraqDbContext db, GuardTriggerRefInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await GuardTriggerRefProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class GuardTriggerRefProcedure
{
	public const string Name = "[croniq].[GuardTriggerRef]";
	public static Task<GuardTriggerRefResult> ExecuteAsync(DbConnection connection, GuardTriggerRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<GuardTriggerRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, GuardTriggerRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<GuardTriggerRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, GuardTriggerRefInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<GuardTriggerRefResult>(interceptorProvider, bindingProvider, connection, GuardTriggerRefPlan.Instance, input, cancellationToken);
	}

}
