// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.GuardTriggerDeadLetterRef</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class GuardTriggerDeadLetterRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<TriggerDeadLetterRef> DeadLetter { get; init; }
}

public readonly record struct GuardTriggerDeadLetterRefInput(
    IReadOnlyList<TriggerDeadLetterRef> DeadLetter
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.GuardTriggerDeadLetterRef</c>.
/// </summary>
public readonly record struct GuardTriggerDeadLetterRefOutput(
    long? TriggerId,
    int? TenantId,
    string? Environment,
    string? Namespace,
    string? Name,
    string? Variant,
    DateTime? FireAtUtc,
    string? DeadLetterReason,
    string? Payload
);

public sealed class GuardTriggerDeadLetterRefResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public GuardTriggerDeadLetterRefOutput? Output { get; init; }
}

internal static class GuardTriggerDeadLetterRefRequestMapper
{
    public static async ValueTask<GuardTriggerDeadLetterRefInput> ToInputAsync(GuardTriggerDeadLetterRefRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new GuardTriggerDeadLetterRefRequest();
        IReadOnlyList<TriggerDeadLetterRef>? DeadLetter = request.DeadLetter;
        if (!HasValue(DeadLetter))
        {
            DeadLetter = await ResolveTableAsync<TriggerDeadLetterRef>(bindingProvider, "[croniq].[GuardTriggerDeadLetterRef]", "@DeadLetter", DeadLetter, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(DeadLetter))
        {
            throw new InvalidOperationException("Parameter @DeadLetter must be supplied by the request or a configured binding.");
        }

        return new GuardTriggerDeadLetterRefInput(
            DeadLetter!
        );
    }

    public static ValueTask<GuardTriggerDeadLetterRefInput> ToInputAsync(GuardTriggerDeadLetterRefRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class GuardTriggerDeadLetterRefPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@DeadLetter", System.Data.DbType.Object, null, false, false, "croniq.TriggerDeadLetterRef"),
            new("@TriggerId", System.Data.DbType.Int64, 8, true, true),
            new("@TenantId", System.Data.DbType.Int32, 4, true, true),
            new("@Environment", System.Data.DbType.String, 32, true, true),
            new("@Namespace", System.Data.DbType.String, 64, true, true),
            new("@Name", System.Data.DbType.String, 128, true, true),
            new("@Variant", System.Data.DbType.String, 64, true, true),
            new("@FireAtUtc", System.Data.DbType.DateTime2, 7, true, true),
            new("@DeadLetterReason", System.Data.DbType.String, 128, true, true),
            new("@Payload", System.Data.DbType.String, null, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new GuardTriggerDeadLetterRefOutput(values.TryGetValue("TriggerId", out var v_TriggerId) ? (long?)v_TriggerId : default, values.TryGetValue("TenantId", out var v_TenantId) ? (int?)v_TenantId : default, values.TryGetValue("Environment", out var v_Environment) ? (string?)v_Environment : default, values.TryGetValue("Namespace", out var v_Namespace) ? (string?)v_Namespace : default, values.TryGetValue("Name", out var v_Name) ? (string?)v_Name : default, values.TryGetValue("Variant", out var v_Variant) ? (string?)v_Variant : default, values.TryGetValue("FireAtUtc", out var v_FireAtUtc) ? (DateTime?)v_FireAtUtc : default, values.TryGetValue("DeadLetterReason", out var v_DeadLetterReason) ? (string?)v_DeadLetterReason : default, values.TryGetValue("Payload", out var v_Payload) ? (string?)v_Payload : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new GuardTriggerDeadLetterRefResult
			{
				Success = success,
				Error = error,
				Output = (GuardTriggerDeadLetterRefOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (GuardTriggerDeadLetterRefInput)state!;
			{ var prm = cmd.Parameters["@DeadLetter"]; var source = input.DeadLetter; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.TriggerDeadLetterRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[GuardTriggerDeadLetterRef]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[GuardTriggerDeadLetterRef]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class GuardTriggerDeadLetterRefExtensions
{
	public static async Task<GuardTriggerDeadLetterRefResult> GuardTriggerDeadLetterRefAsync(this IXtraqDbContext db, GuardTriggerDeadLetterRefRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await GuardTriggerDeadLetterRefRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await GuardTriggerDeadLetterRefAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<GuardTriggerDeadLetterRefResult> GuardTriggerDeadLetterRefAsync(this IXtraqDbContext db, GuardTriggerDeadLetterRefInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await GuardTriggerDeadLetterRefProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class GuardTriggerDeadLetterRefProcedure
{
	public const string Name = "[croniq].[GuardTriggerDeadLetterRef]";
	public static Task<GuardTriggerDeadLetterRefResult> ExecuteAsync(DbConnection connection, GuardTriggerDeadLetterRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<GuardTriggerDeadLetterRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, GuardTriggerDeadLetterRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<GuardTriggerDeadLetterRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, GuardTriggerDeadLetterRefInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<GuardTriggerDeadLetterRefResult>(interceptorProvider, bindingProvider, connection, GuardTriggerDeadLetterRefPlan.Instance, input, cancellationToken);
	}

}
