// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.GuardInstanceRef</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class GuardInstanceRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<InstanceRef> Instance { get; init; }
}

public readonly record struct GuardInstanceRefInput(
    IReadOnlyList<InstanceRef> Instance
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.GuardInstanceRef</c>.
/// </summary>
public readonly record struct GuardInstanceRefOutput(
    string? InstanceId,
    string? Environment,
    string? NodeName,
    string? Capabilities,
    string? Version
);

public sealed class GuardInstanceRefResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public GuardInstanceRefOutput? Output { get; init; }
}

internal static class GuardInstanceRefRequestMapper
{
    public static async ValueTask<GuardInstanceRefInput> ToInputAsync(GuardInstanceRefRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new GuardInstanceRefRequest();
        IReadOnlyList<InstanceRef>? Instance = request.Instance;
        if (!HasValue(Instance))
        {
            Instance = await ResolveTableAsync<InstanceRef>(bindingProvider, "[croniq].[GuardInstanceRef]", "@Instance", Instance, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Instance))
        {
            throw new InvalidOperationException("Parameter @Instance must be supplied by the request or a configured binding.");
        }

        return new GuardInstanceRefInput(
            Instance!
        );
    }

    public static ValueTask<GuardInstanceRefInput> ToInputAsync(GuardInstanceRefRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class GuardInstanceRefPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Instance", System.Data.DbType.Object, null, false, false, "croniq.InstanceRef"),
            new("@InstanceId", System.Data.DbType.String, 64, true, true),
            new("@Environment", System.Data.DbType.String, 32, true, true),
            new("@NodeName", System.Data.DbType.String, 64, true, true),
            new("@Capabilities", System.Data.DbType.String, null, true, true),
            new("@Version", System.Data.DbType.String, 64, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new GuardInstanceRefOutput(values.TryGetValue("InstanceId", out var v_InstanceId) ? (string?)v_InstanceId : default, values.TryGetValue("Environment", out var v_Environment) ? (string?)v_Environment : default, values.TryGetValue("NodeName", out var v_NodeName) ? (string?)v_NodeName : default, values.TryGetValue("Capabilities", out var v_Capabilities) ? (string?)v_Capabilities : default, values.TryGetValue("Version", out var v_Version) ? (string?)v_Version : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new GuardInstanceRefResult
			{
				Success = success,
				Error = error,
				Output = (GuardInstanceRefOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (GuardInstanceRefInput)state!;
			{ var prm = cmd.Parameters["@Instance"]; var source = input.Instance; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.InstanceRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[GuardInstanceRef]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[GuardInstanceRef]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class GuardInstanceRefExtensions
{
	public static async Task<GuardInstanceRefResult> GuardInstanceRefAsync(this IXtraqDbContext db, GuardInstanceRefRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await GuardInstanceRefRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await GuardInstanceRefAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<GuardInstanceRefResult> GuardInstanceRefAsync(this IXtraqDbContext db, GuardInstanceRefInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await GuardInstanceRefProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class GuardInstanceRefProcedure
{
	public const string Name = "[croniq].[GuardInstanceRef]";
	public static Task<GuardInstanceRefResult> ExecuteAsync(DbConnection connection, GuardInstanceRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<GuardInstanceRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, GuardInstanceRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<GuardInstanceRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, GuardInstanceRefInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<GuardInstanceRefResult>(interceptorProvider, bindingProvider, connection, GuardInstanceRefPlan.Instance, input, cancellationToken);
	}

}
