// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.GuardJobRef</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class GuardJobRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<JobRef> Job { get; init; }
}

public readonly record struct GuardJobRefInput(
    IReadOnlyList<JobRef> Job
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.GuardJobRef</c>.
/// </summary>
public readonly record struct GuardJobRefOutput(
    string? JobKey,
    int? TenantId,
    string? Environment,
    string? Namespace,
    string? Name,
    string? Variant,
    string? Description,
    string? Metadata
);

public sealed class GuardJobRefResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public GuardJobRefOutput? Output { get; init; }
}

internal static class GuardJobRefRequestMapper
{
    public static async ValueTask<GuardJobRefInput> ToInputAsync(GuardJobRefRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new GuardJobRefRequest();
        IReadOnlyList<JobRef>? Job = request.Job;
        if (!HasValue(Job))
        {
            Job = await ResolveTableAsync<JobRef>(bindingProvider, "[croniq].[GuardJobRef]", "@Job", Job, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Job))
        {
            throw new InvalidOperationException("Parameter @Job must be supplied by the request or a configured binding.");
        }

        return new GuardJobRefInput(
            Job!
        );
    }

    public static ValueTask<GuardJobRefInput> ToInputAsync(GuardJobRefRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class GuardJobRefPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Job", System.Data.DbType.Object, null, false, false, "croniq.JobRef"),
            new("@JobKey", System.Data.DbType.String, 64, true, true),
            new("@TenantId", System.Data.DbType.Int32, 4, true, true),
            new("@Environment", System.Data.DbType.String, 32, true, true),
            new("@Namespace", System.Data.DbType.String, 64, true, true),
            new("@Name", System.Data.DbType.String, 128, true, true),
            new("@Variant", System.Data.DbType.String, 64, true, true),
            new("@Description", System.Data.DbType.String, 64, true, true),
            new("@Metadata", System.Data.DbType.String, null, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new GuardJobRefOutput(values.TryGetValue("JobKey", out var v_JobKey) ? (string?)v_JobKey : default, values.TryGetValue("TenantId", out var v_TenantId) ? (int?)v_TenantId : default, values.TryGetValue("Environment", out var v_Environment) ? (string?)v_Environment : default, values.TryGetValue("Namespace", out var v_Namespace) ? (string?)v_Namespace : default, values.TryGetValue("Name", out var v_Name) ? (string?)v_Name : default, values.TryGetValue("Variant", out var v_Variant) ? (string?)v_Variant : default, values.TryGetValue("Description", out var v_Description) ? (string?)v_Description : default, values.TryGetValue("Metadata", out var v_Metadata) ? (string?)v_Metadata : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new GuardJobRefResult
			{
				Success = success,
				Error = error,
				Output = (GuardJobRefOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (GuardJobRefInput)state!;
			{ var prm = cmd.Parameters["@Job"]; var source = input.Job; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.JobRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[GuardJobRef]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[GuardJobRef]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class GuardJobRefExtensions
{
	public static async Task<GuardJobRefResult> GuardJobRefAsync(this IXtraqDbContext db, GuardJobRefRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await GuardJobRefRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await GuardJobRefAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<GuardJobRefResult> GuardJobRefAsync(this IXtraqDbContext db, GuardJobRefInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await GuardJobRefProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class GuardJobRefProcedure
{
	public const string Name = "[croniq].[GuardJobRef]";
	public static Task<GuardJobRefResult> ExecuteAsync(DbConnection connection, GuardJobRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<GuardJobRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, GuardJobRefInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<GuardJobRefResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, GuardJobRefInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<GuardJobRefResult>(interceptorProvider, bindingProvider, connection, GuardJobRefPlan.Instance, input, cancellationToken);
	}

}
