// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.InstanceHeartbeat</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class InstanceHeartbeatRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<InstanceRefRequest> Instance { get; init; } = default!;
}

public readonly record struct InstanceHeartbeatInput(
    IReadOnlyList<ActorRef> Actor,
    IReadOnlyList<InstanceRef> Instance
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.InstanceHeartbeat</c>.
/// </summary>
public readonly record struct InstanceHeartbeatOutput(
    int? Generation,
    DateTime? LastSeenUtc
);

public sealed class InstanceHeartbeatResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public InstanceHeartbeatOutput? Output { get; init; }
}
internal static class InstanceHeartbeatRequestMapper
{
    public static async ValueTask<InstanceHeartbeatInput> ToInputAsync(InstanceHeartbeatRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new InstanceHeartbeatRequest();
        IReadOnlyList<ActorRef>? Actor = default;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[InstanceHeartbeat]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        IReadOnlyList<InstanceRef>? Instance = InstanceRefRequest.ToTableTypes(request.Instance);
        if (!HasValue(Instance))
        {
            Instance = await ResolveTableAsync<InstanceRef>(bindingProvider, "[croniq].[InstanceHeartbeat]", "@Instance", Instance, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Instance))
        {
            throw new InvalidOperationException("Parameter @Instance must be supplied by the request or a configured binding.");
        }

        return new InstanceHeartbeatInput(
            Actor!,
            Instance!
        );
    }

    public static ValueTask<InstanceHeartbeatInput> ToInputAsync(InstanceHeartbeatRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class InstanceHeartbeatPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@Instance", System.Data.DbType.Object, null, false, false, "croniq.InstanceRef"),
            new("@Generation", System.Data.DbType.Int32, 4, true, true),
            new("@LastSeenUtc", System.Data.DbType.DateTime2, 7, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new InstanceHeartbeatOutput(values.TryGetValue("Generation", out var v_Generation) ? (int?)v_Generation : default, values.TryGetValue("LastSeenUtc", out var v_LastSeenUtc) ? (DateTime?)v_LastSeenUtc : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new InstanceHeartbeatResult
			{
				Success = success,
				Error = error,
				Output = (InstanceHeartbeatOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (InstanceHeartbeatInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			{ var prm = cmd.Parameters["@Instance"]; var source = input.Instance; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.InstanceRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[InstanceHeartbeat]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[InstanceHeartbeat]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class InstanceHeartbeatExtensions
{
	public static async Task<InstanceHeartbeatResult> InstanceHeartbeatAsync(this IXtraqDbContext db, InstanceHeartbeatRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await InstanceHeartbeatRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await InstanceHeartbeatAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<InstanceHeartbeatResult> InstanceHeartbeatAsync(this IXtraqDbContext db, InstanceHeartbeatInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await InstanceHeartbeatProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class InstanceHeartbeatProcedure
{
	public const string Name = "[croniq].[InstanceHeartbeat]";
	public static Task<InstanceHeartbeatResult> ExecuteAsync(DbConnection connection, InstanceHeartbeatInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<InstanceHeartbeatResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, InstanceHeartbeatInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<InstanceHeartbeatResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, InstanceHeartbeatInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<InstanceHeartbeatResult>(interceptorProvider, bindingProvider, connection, InstanceHeartbeatPlan.Instance, input, cancellationToken);
	}

}
