// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.JobFindByKey</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class JobFindByKeyRequest
{
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string? JobKey { get; init; }
}

public readonly record struct JobFindByKeyInput(
    IReadOnlyList<ActorRef> Actor,
    string? JobKey
);

/// <summary>
/// Represents the result set <c>ResultSet1</c> emitted by <c>croniq.ResultSet1</c>.
/// </summary>
public readonly record struct JobFindByKeyResultSet1Result(
    long JobId,
    string JobKey,
    int TenantId,
    string Environment,
    string Namespace,
    string Name,
    string? Variant,
    string? Description,
    string? Metadata,
    DateTime CreatedUtc,
    DateTime? UpdatedUtc,
    bool IsDeleted
);

public sealed class JobFindByKeyResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// Result set <c>ResultSet1</c> projected as a strongly typed sequence.
	/// </summary>
	public JobFindByKeyResultSet1Result? Result { get; init; } = null;
	/// <summary>
	/// Raw JSON payload captured for result set <c>ResultSet1</c>.
	/// </summary>
	public string? ResultRawJson { get; init; } = null;
}
internal static class JobFindByKeyRequestMapper
{
    public static async ValueTask<JobFindByKeyInput> ToInputAsync(JobFindByKeyRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new JobFindByKeyRequest();
        IReadOnlyList<ActorRef>? Actor = default;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[JobFindByKey]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        string? JobKey = request.JobKey;
        if (!HasValue(JobKey))
        {
	    JobKey = await ResolveAsync<string?>(bindingProvider, "[croniq].[JobFindByKey]", "@JobKey", false, JobKey, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(JobKey))
        {
            throw new InvalidOperationException("Parameter @JobKey must be supplied by the request or a configured binding.");
        }

        return new JobFindByKeyInput(
            Actor!,
            JobKey
        );
    }

    public static ValueTask<JobFindByKeyInput> ToInputAsync(JobFindByKeyRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class JobFindByKeyPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@JobKey", System.Data.DbType.String, 64, false, true),
        };

		var resultSets = new ResultSetMapping[]
		{
            new("ResultSet1", async (r, ct) =>
			{
                var list = new System.Collections.Generic.List<object>();
                var __sb = new System.Text.StringBuilder();
                while (await r.ReadAsync(ct).ConfigureAwait(false))
                {
                    if (!r.IsDBNull(0))
                    {
                        __sb.Append(r.GetString(0));
                    }
                }
                var __raw = __sb.Length > 0 ? __sb.ToString() : null;
                var __items = new System.Collections.Generic.List<JobFindByKeyResultSet1Result>();
                if (__raw != null)
                {
                    try
                    {
                        var __parsed = System.Text.Json.JsonSerializer.Deserialize<JobFindByKeyResultSet1Result?>(__raw, JsonSupport.Options);
                        if (__parsed is { } __value)
                        {
                            __items.Add(__value);
                        }
                    }
                    catch
                    {
                    }
                }
                list.Add(JsonResultEnvelope<JobFindByKeyResultSet1Result>.Create(__items, __raw));
                return list;
			}),

        };

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new JobFindByKeyResult
			{
				Success = success,
				Error = error,
				// ResultSet 0 -> Result
				Result = rs.Length > 0 && rs[0] is object[] rows0 && rows0.Length > 0 && rows0[0] is JsonResultEnvelope<JobFindByKeyResultSet1Result> env0 && env0.TryGetFirst(out var value0) ? value0 : (JobFindByKeyResultSet1Result?)null,
				ResultRawJson = rs.Length > 0 && rs[0] is object[] rows0_raw && rows0_raw.Length > 0 && rows0_raw[0] is JsonResultEnvelope<JobFindByKeyResultSet1Result> env0_raw ? env0_raw.RawJson : null
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (JobFindByKeyInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			cmd.Parameters["@JobKey"].Value = (object?)input.JobKey ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[croniq].[JobFindByKey]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[JobFindByKey]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class JobFindByKeyExtensions
{
	public static async Task<JobFindByKeyResult> JobFindByKeyAsync(this IXtraqDbContext db, JobFindByKeyRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await JobFindByKeyRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await JobFindByKeyAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<JobFindByKeyResult> JobFindByKeyAsync(this IXtraqDbContext db, JobFindByKeyInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await JobFindByKeyProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class JobFindByKeyProcedure
{
	public const string Name = "[croniq].[JobFindByKey]";
	public static Task<JobFindByKeyResult> ExecuteAsync(DbConnection connection, JobFindByKeyInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<JobFindByKeyResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, JobFindByKeyInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<JobFindByKeyResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, JobFindByKeyInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<JobFindByKeyResult>(interceptorProvider, bindingProvider, connection, JobFindByKeyPlan.Instance, input, cancellationToken);
	}

}
