// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.ThrowTriggerLeaseReleaseRefIncomplete</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
public sealed class ThrowTriggerLeaseReleaseRefIncompleteResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
}

internal static class ThrowTriggerLeaseReleaseRefIncompleteRequestMapper
{
    public static async ValueTask<ThrowTriggerLeaseReleaseRefIncompleteInput> ToInputAsync(ThrowTriggerLeaseReleaseRefIncompleteRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new ThrowTriggerLeaseReleaseRefIncompleteRequest();

        return new ThrowTriggerLeaseReleaseRefIncompleteInput(
        );
    }

    public static ValueTask<ThrowTriggerLeaseReleaseRefIncompleteInput> ToInputAsync(ThrowTriggerLeaseReleaseRefIncompleteRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class ThrowTriggerLeaseReleaseRefIncompletePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = Array.Empty<ProcedureParameter>();

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => null;
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new ThrowTriggerLeaseReleaseRefIncompleteResult
			{
				Success = success,
				Error = error
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
		}
		return new ProcedureExecutionPlan(
			"[croniq].[ThrowTriggerLeaseReleaseRefIncomplete]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[ThrowTriggerLeaseReleaseRefIncomplete]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class ThrowTriggerLeaseReleaseRefIncompleteExtensions
{

	public static async Task<ThrowTriggerLeaseReleaseRefIncompleteResult> ThrowTriggerLeaseReleaseRefIncompleteAsync(this IXtraqDbContext db, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await ThrowTriggerLeaseReleaseRefIncompleteProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class ThrowTriggerLeaseReleaseRefIncompleteProcedure
{
	public const string Name = "[croniq].[ThrowTriggerLeaseReleaseRefIncomplete]";
	public static Task<ThrowTriggerLeaseReleaseRefIncompleteResult> ExecuteAsync(DbConnection connection, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, cancellationToken);

	public static Task<ThrowTriggerLeaseReleaseRefIncompleteResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, cancellationToken);

	public static Task<ThrowTriggerLeaseReleaseRefIncompleteResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<ThrowTriggerLeaseReleaseRefIncompleteResult>(interceptorProvider, bindingProvider, connection, ThrowTriggerLeaseReleaseRefIncompletePlan.Instance, null, cancellationToken);
	}

}
