// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.TriggerRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record TriggerRef : ITableType
{
    public string TriggerKey { get; init; } = string.Empty;
    public string JobKey { get; init; } = string.Empty;
    public int TenantId { get; init; }
    public long JobId { get; init; }
    public string Environment { get; init; } = string.Empty;
    public string Namespace { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string? Variant { get; init; }
    public string CronExpression { get; init; } = string.Empty;
    public string TimeZoneId { get; init; } = string.Empty;
    public DateTime? StartAtUtc { get; init; }
    public DateTime? EndAtUtc { get; init; }
    public bool Enabled { get; init; }
    public string? Metadata { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public TriggerRef() { }

	public static TriggerRef Create(
        string TriggerKey,
        string JobKey,
        int TenantId,
        long JobId,
        string Environment,
        string Namespace,
        string Name,
        string? Variant,
        string CronExpression,
        string TimeZoneId,
        DateTime? StartAtUtc,
        DateTime? EndAtUtc,
        bool Enabled,
        string? Metadata
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new TriggerRef
    {
        TriggerKey = TriggerKey,
        JobKey = JobKey,
        TenantId = TenantId,
        JobId = JobId,
        Environment = Environment,
        Namespace = Namespace,
        Name = Name,
        Variant = Variant,
        CronExpression = CronExpression,
        TimeZoneId = TimeZoneId,
        StartAtUtc = StartAtUtc,
        EndAtUtc = EndAtUtc,
        Enabled = Enabled,
        Metadata = Metadata
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class TriggerRefBuilder
	{
        private string _TriggerKey = string.Empty;
        private string _JobKey = string.Empty;
        private int _TenantId;
        private long _JobId;
        private string _Environment = string.Empty;
        private string _Namespace = string.Empty;
        private string _Name = string.Empty;
        private string? _Variant;
        private string _CronExpression = string.Empty;
        private string _TimeZoneId = string.Empty;
        private DateTime? _StartAtUtc;
        private DateTime? _EndAtUtc;
        private bool _Enabled;
        private string? _Metadata;
        public TriggerRefBuilder WithTriggerKey(string value) { _TriggerKey = value; return this; }
        public TriggerRefBuilder WithJobKey(string value) { _JobKey = value; return this; }
        public TriggerRefBuilder WithTenantId(int value) { _TenantId = value; return this; }
        public TriggerRefBuilder WithJobId(long value) { _JobId = value; return this; }
        public TriggerRefBuilder WithEnvironment(string value) { _Environment = value; return this; }
        public TriggerRefBuilder WithNamespace(string value) { _Namespace = value; return this; }
        public TriggerRefBuilder WithName(string value) { _Name = value; return this; }
        public TriggerRefBuilder WithVariant(string? value) { _Variant = value; return this; }
        public TriggerRefBuilder WithCronExpression(string value) { _CronExpression = value; return this; }
        public TriggerRefBuilder WithTimeZoneId(string value) { _TimeZoneId = value; return this; }
        public TriggerRefBuilder WithStartAtUtc(DateTime? value) { _StartAtUtc = value; return this; }
        public TriggerRefBuilder WithEndAtUtc(DateTime? value) { _EndAtUtc = value; return this; }
        public TriggerRefBuilder WithEnabled(bool value) { _Enabled = value; return this; }
        public TriggerRefBuilder WithMetadata(string? value) { _Metadata = value; return this; }
        public TriggerRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new TriggerRef
            {
                TriggerKey = _TriggerKey,
                JobKey = _JobKey,
                TenantId = _TenantId,
                JobId = _JobId,
                Environment = _Environment,
                Namespace = _Namespace,
                Name = _Name,
                Variant = _Variant,
                CronExpression = _CronExpression,
                TimeZoneId = _TimeZoneId,
                StartAtUtc = _StartAtUtc,
                EndAtUtc = _EndAtUtc,
                Enabled = _Enabled,
                Metadata = _Metadata
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

