// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.TriggerLeaseReleaseRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record TriggerLeaseReleaseRef : ITableType
{
    public long LeaseId { get; init; }
    public string InstanceId { get; init; } = string.Empty;

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public TriggerLeaseReleaseRef() { }

	public static TriggerLeaseReleaseRef Create(
        long LeaseId,
        string InstanceId
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new TriggerLeaseReleaseRef
    {
        LeaseId = LeaseId,
        InstanceId = InstanceId
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class TriggerLeaseReleaseRefBuilder
	{
        private long _LeaseId;
        private string _InstanceId = string.Empty;
        public TriggerLeaseReleaseRefBuilder WithLeaseId(long value) { _LeaseId = value; return this; }
        public TriggerLeaseReleaseRefBuilder WithInstanceId(string value) { _InstanceId = value; return this; }
        public TriggerLeaseReleaseRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new TriggerLeaseReleaseRef
            {
                LeaseId = _LeaseId,
                InstanceId = _InstanceId
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

