// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.TriggerLeaseRelease</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class TriggerLeaseReleaseRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<TriggerLeaseReleaseRefRequest> Release { get; init; }
}

public readonly record struct TriggerLeaseReleaseInput(
    IReadOnlyList<ActorRef> Actor,
    IReadOnlyList<TriggerLeaseReleaseRef> Release
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.TriggerLeaseRelease</c>.
/// </summary>
public readonly record struct TriggerLeaseReleaseOutput(
    int? ReleasedCount
);

public sealed class TriggerLeaseReleaseResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public TriggerLeaseReleaseOutput? Output { get; init; }
}

internal static class TriggerLeaseReleaseRequestMapper
{
    public static async ValueTask<TriggerLeaseReleaseInput> ToInputAsync(TriggerLeaseReleaseRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new TriggerLeaseReleaseRequest();
        IReadOnlyList<ActorRef>? Actor = default;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[TriggerLeaseRelease]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        IReadOnlyList<TriggerLeaseReleaseRef>? Release = TriggerLeaseReleaseRefRequest.ToTableTypes(request.Release);
        if (!HasValue(Release))
        {
            Release = await ResolveTableAsync<TriggerLeaseReleaseRef>(bindingProvider, "[croniq].[TriggerLeaseRelease]", "@Release", Release, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Release))
        {
            throw new InvalidOperationException("Parameter @Release must be supplied by the request or a configured binding.");
        }

        return new TriggerLeaseReleaseInput(
            Actor!,
            Release!
        );
    }

    public static ValueTask<TriggerLeaseReleaseInput> ToInputAsync(TriggerLeaseReleaseRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class TriggerLeaseReleasePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@Release", System.Data.DbType.Object, null, false, false, "croniq.TriggerLeaseReleaseRef"),
            new("@ReleasedCount", System.Data.DbType.Int32, 4, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new TriggerLeaseReleaseOutput(values.TryGetValue("ReleasedCount", out var v_ReleasedCount) ? (int?)v_ReleasedCount : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new TriggerLeaseReleaseResult
			{
				Success = success,
				Error = error,
				Output = (TriggerLeaseReleaseOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (TriggerLeaseReleaseInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			{ var prm = cmd.Parameters["@Release"]; var source = input.Release; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.TriggerLeaseReleaseRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[TriggerLeaseRelease]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[TriggerLeaseRelease]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class TriggerLeaseReleaseExtensions
{
	public static async Task<TriggerLeaseReleaseResult> TriggerLeaseReleaseAsync(this IXtraqDbContext db, TriggerLeaseReleaseRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await TriggerLeaseReleaseRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await TriggerLeaseReleaseAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<TriggerLeaseReleaseResult> TriggerLeaseReleaseAsync(this IXtraqDbContext db, TriggerLeaseReleaseInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await TriggerLeaseReleaseProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class TriggerLeaseReleaseProcedure
{
	public const string Name = "[croniq].[TriggerLeaseRelease]";
	public static Task<TriggerLeaseReleaseResult> ExecuteAsync(DbConnection connection, TriggerLeaseReleaseInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<TriggerLeaseReleaseResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, TriggerLeaseReleaseInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<TriggerLeaseReleaseResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, TriggerLeaseReleaseInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<TriggerLeaseReleaseResult>(interceptorProvider, bindingProvider, connection, TriggerLeaseReleasePlan.Instance, input, cancellationToken);
	}

}
