// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.TriggerLeaseRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record TriggerLeaseRef : ITableType
{
    public long TriggerId { get; init; }
    public long JobId { get; init; }
    public int TenantId { get; init; }
    public string Environment { get; init; } = string.Empty;
    public string Namespace { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string? Variant { get; init; }
    public string InstanceId { get; init; } = string.Empty;
    public DateTime FireAtUtc { get; init; }
    public DateTime LeaseExpiresAtUtc { get; init; }
    public string? Payload { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public TriggerLeaseRef() { }

	public static TriggerLeaseRef Create(
        long TriggerId,
        long JobId,
        int TenantId,
        string Environment,
        string Namespace,
        string Name,
        string? Variant,
        string InstanceId,
        DateTime FireAtUtc,
        DateTime LeaseExpiresAtUtc,
        string? Payload
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new TriggerLeaseRef
    {
        TriggerId = TriggerId,
        JobId = JobId,
        TenantId = TenantId,
        Environment = Environment,
        Namespace = Namespace,
        Name = Name,
        Variant = Variant,
        InstanceId = InstanceId,
        FireAtUtc = FireAtUtc,
        LeaseExpiresAtUtc = LeaseExpiresAtUtc,
        Payload = Payload
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class TriggerLeaseRefBuilder
	{
        private long _TriggerId;
        private long _JobId;
        private int _TenantId;
        private string _Environment = string.Empty;
        private string _Namespace = string.Empty;
        private string _Name = string.Empty;
        private string? _Variant;
        private string _InstanceId = string.Empty;
        private DateTime _FireAtUtc;
        private DateTime _LeaseExpiresAtUtc;
        private string? _Payload;
        public TriggerLeaseRefBuilder WithTriggerId(long value) { _TriggerId = value; return this; }
        public TriggerLeaseRefBuilder WithJobId(long value) { _JobId = value; return this; }
        public TriggerLeaseRefBuilder WithTenantId(int value) { _TenantId = value; return this; }
        public TriggerLeaseRefBuilder WithEnvironment(string value) { _Environment = value; return this; }
        public TriggerLeaseRefBuilder WithNamespace(string value) { _Namespace = value; return this; }
        public TriggerLeaseRefBuilder WithName(string value) { _Name = value; return this; }
        public TriggerLeaseRefBuilder WithVariant(string? value) { _Variant = value; return this; }
        public TriggerLeaseRefBuilder WithInstanceId(string value) { _InstanceId = value; return this; }
        public TriggerLeaseRefBuilder WithFireAtUtc(DateTime value) { _FireAtUtc = value; return this; }
        public TriggerLeaseRefBuilder WithLeaseExpiresAtUtc(DateTime value) { _LeaseExpiresAtUtc = value; return this; }
        public TriggerLeaseRefBuilder WithPayload(string? value) { _Payload = value; return this; }
        public TriggerLeaseRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new TriggerLeaseRef
            {
                TriggerId = _TriggerId,
                JobId = _JobId,
                TenantId = _TenantId,
                Environment = _Environment,
                Namespace = _Namespace,
                Name = _Name,
                Variant = _Variant,
                InstanceId = _InstanceId,
                FireAtUtc = _FireAtUtc,
                LeaseExpiresAtUtc = _LeaseExpiresAtUtc,
                Payload = _Payload
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

