// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.TriggerDeadLetterRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record TriggerDeadLetterRef : ITableType
{
    public long TriggerId { get; init; }
    public int TenantId { get; init; }
    public string Environment { get; init; } = string.Empty;
    public string Namespace { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string? Variant { get; init; }
    public DateTime FireAtUtc { get; init; }
    public string? DeadLetterReason { get; init; }
    public string? Payload { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public TriggerDeadLetterRef() { }

	public static TriggerDeadLetterRef Create(
        long TriggerId,
        int TenantId,
        string Environment,
        string Namespace,
        string Name,
        string? Variant,
        DateTime FireAtUtc,
        string? DeadLetterReason,
        string? Payload
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new TriggerDeadLetterRef
    {
        TriggerId = TriggerId,
        TenantId = TenantId,
        Environment = Environment,
        Namespace = Namespace,
        Name = Name,
        Variant = Variant,
        FireAtUtc = FireAtUtc,
        DeadLetterReason = DeadLetterReason,
        Payload = Payload
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class TriggerDeadLetterRefBuilder
	{
        private long _TriggerId;
        private int _TenantId;
        private string _Environment = string.Empty;
        private string _Namespace = string.Empty;
        private string _Name = string.Empty;
        private string? _Variant;
        private DateTime _FireAtUtc;
        private string? _DeadLetterReason;
        private string? _Payload;
        public TriggerDeadLetterRefBuilder WithTriggerId(long value) { _TriggerId = value; return this; }
        public TriggerDeadLetterRefBuilder WithTenantId(int value) { _TenantId = value; return this; }
        public TriggerDeadLetterRefBuilder WithEnvironment(string value) { _Environment = value; return this; }
        public TriggerDeadLetterRefBuilder WithNamespace(string value) { _Namespace = value; return this; }
        public TriggerDeadLetterRefBuilder WithName(string value) { _Name = value; return this; }
        public TriggerDeadLetterRefBuilder WithVariant(string? value) { _Variant = value; return this; }
        public TriggerDeadLetterRefBuilder WithFireAtUtc(DateTime value) { _FireAtUtc = value; return this; }
        public TriggerDeadLetterRefBuilder WithDeadLetterReason(string? value) { _DeadLetterReason = value; return this; }
        public TriggerDeadLetterRefBuilder WithPayload(string? value) { _Payload = value; return this; }
        public TriggerDeadLetterRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new TriggerDeadLetterRef
            {
                TriggerId = _TriggerId,
                TenantId = _TenantId,
                Environment = _Environment,
                Namespace = _Namespace,
                Name = _Name,
                Variant = _Variant,
                FireAtUtc = _FireAtUtc,
                DeadLetterReason = _DeadLetterReason,
                Payload = _Payload
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

