// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.TriggerDelete</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class TriggerDeleteRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<ActorRef> Actor { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<TriggerRef> Trigger { get; init; }
}

public readonly record struct TriggerDeleteInput(
    IReadOnlyList<ActorRef> Actor,
    IReadOnlyList<TriggerRef> Trigger
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.TriggerDelete</c>.
/// </summary>
public readonly record struct TriggerDeleteOutput(
    long? TriggerId,
    DateTime? UpdatedUtc
);

public sealed class TriggerDeleteResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public TriggerDeleteOutput? Output { get; init; }
}

internal static class TriggerDeleteRequestMapper
{
    public static async ValueTask<TriggerDeleteInput> ToInputAsync(TriggerDeleteRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new TriggerDeleteRequest();
        IReadOnlyList<ActorRef>? Actor = request.Actor;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[TriggerDelete]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        IReadOnlyList<TriggerRef>? Trigger = request.Trigger;
        if (!HasValue(Trigger))
        {
            Trigger = await ResolveTableAsync<TriggerRef>(bindingProvider, "[croniq].[TriggerDelete]", "@Trigger", Trigger, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Trigger))
        {
            throw new InvalidOperationException("Parameter @Trigger must be supplied by the request or a configured binding.");
        }

        return new TriggerDeleteInput(
            Actor!,
            Trigger!
        );
    }

    public static ValueTask<TriggerDeleteInput> ToInputAsync(TriggerDeleteRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class TriggerDeletePlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@Trigger", System.Data.DbType.Object, null, false, false, "croniq.TriggerRef"),
            new("@TriggerId", System.Data.DbType.Int64, 8, true, true),
            new("@UpdatedUtc", System.Data.DbType.DateTime2, 7, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new TriggerDeleteOutput(values.TryGetValue("TriggerId", out var v_TriggerId) ? (long?)v_TriggerId : default, values.TryGetValue("UpdatedUtc", out var v_UpdatedUtc) ? (DateTime?)v_UpdatedUtc : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new TriggerDeleteResult
			{
				Success = success,
				Error = error,
				Output = (TriggerDeleteOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (TriggerDeleteInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			{ var prm = cmd.Parameters["@Trigger"]; var source = input.Trigger; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.TriggerRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[TriggerDelete]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[TriggerDelete]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class TriggerDeleteExtensions
{
	public static async Task<TriggerDeleteResult> TriggerDeleteAsync(this IXtraqDbContext db, TriggerDeleteRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await TriggerDeleteRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await TriggerDeleteAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<TriggerDeleteResult> TriggerDeleteAsync(this IXtraqDbContext db, TriggerDeleteInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await TriggerDeleteProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class TriggerDeleteProcedure
{
	public const string Name = "[croniq].[TriggerDelete]";
	public static Task<TriggerDeleteResult> ExecuteAsync(DbConnection connection, TriggerDeleteInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<TriggerDeleteResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, TriggerDeleteInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<TriggerDeleteResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, TriggerDeleteInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<TriggerDeleteResult>(interceptorProvider, bindingProvider, connection, TriggerDeletePlan.Instance, input, cancellationToken);
	}

}
