// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.TriggerDeadLetterRetention</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class TriggerDeadLetterRetentionRequest
{
    public int? RetentionDays { get; init; }
}

public readonly record struct TriggerDeadLetterRetentionInput(
    IReadOnlyList<ActorRef> Actor,
    int? RetentionDays
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.TriggerDeadLetterRetention</c>.
/// </summary>
public readonly record struct TriggerDeadLetterRetentionOutput(
    int? DeletedCount
);

public sealed class TriggerDeadLetterRetentionResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public TriggerDeadLetterRetentionOutput? Output { get; init; }
}

internal static class TriggerDeadLetterRetentionRequestMapper
{
    public static async ValueTask<TriggerDeadLetterRetentionInput> ToInputAsync(TriggerDeadLetterRetentionRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new TriggerDeadLetterRetentionRequest();
        IReadOnlyList<ActorRef>? Actor = default;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[TriggerDeadLetterRetention]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        int? RetentionDays = request.RetentionDays;
        if (!HasValue(RetentionDays))
        {
	    RetentionDays = await ResolveAsync<int?>(bindingProvider, "[croniq].[TriggerDeadLetterRetention]", "@RetentionDays", false, RetentionDays, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(RetentionDays))
        {
            throw new InvalidOperationException("Parameter @RetentionDays must be supplied by the request or a configured binding.");
        }

        return new TriggerDeadLetterRetentionInput(
            Actor!,
            RetentionDays
        );
    }

    public static ValueTask<TriggerDeadLetterRetentionInput> ToInputAsync(TriggerDeadLetterRetentionRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class TriggerDeadLetterRetentionPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@RetentionDays", System.Data.DbType.Int32, 4, false, true),
            new("@DeletedCount", System.Data.DbType.Int32, 4, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new TriggerDeadLetterRetentionOutput(values.TryGetValue("DeletedCount", out var v_DeletedCount) ? (int?)v_DeletedCount : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new TriggerDeadLetterRetentionResult
			{
				Success = success,
				Error = error,
				Output = (TriggerDeadLetterRetentionOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (TriggerDeadLetterRetentionInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			cmd.Parameters["@RetentionDays"].Value = (object?)input.RetentionDays ?? DBNull.Value;
		}
		return new ProcedureExecutionPlan(
			"[croniq].[TriggerDeadLetterRetention]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[TriggerDeadLetterRetention]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class TriggerDeadLetterRetentionExtensions
{
	public static async Task<TriggerDeadLetterRetentionResult> TriggerDeadLetterRetentionAsync(this IXtraqDbContext db, TriggerDeadLetterRetentionRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await TriggerDeadLetterRetentionRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await TriggerDeadLetterRetentionAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<TriggerDeadLetterRetentionResult> TriggerDeadLetterRetentionAsync(this IXtraqDbContext db, TriggerDeadLetterRetentionInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await TriggerDeadLetterRetentionProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class TriggerDeadLetterRetentionProcedure
{
	public const string Name = "[croniq].[TriggerDeadLetterRetention]";
	public static Task<TriggerDeadLetterRetentionResult> ExecuteAsync(DbConnection connection, TriggerDeadLetterRetentionInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<TriggerDeadLetterRetentionResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, TriggerDeadLetterRetentionInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<TriggerDeadLetterRetentionResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, TriggerDeadLetterRetentionInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<TriggerDeadLetterRetentionResult>(interceptorProvider, bindingProvider, connection, TriggerDeadLetterRetentionPlan.Instance, input, cancellationToken);
	}

}
