// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable

using global::Croniq.Persistence.Xtraq;
using global::Croniq.Persistence.Xtraq.Core;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Represents the contract for the stored procedure <c>croniq.TriggerDeadLetterInsert</c> including parameters, result sets and execution metadata.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI. To change this artifact, modify the underlying SQL stored procedure definition.
/// </remarks>
/// <summary>
/// Request DTO for external callers. Missing values can be hydrated from <see cref="IXtraqParameterBindingProvider"/>.
/// </summary>
public sealed record class TriggerDeadLetterInsertRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    public IReadOnlyList<TriggerDeadLetterRefRequest> DeadLetter { get; init; }
}

public readonly record struct TriggerDeadLetterInsertInput(
    IReadOnlyList<ActorRef> Actor,
    IReadOnlyList<TriggerDeadLetterRef> DeadLetter
);

/// <summary>
/// Captures OUTPUT parameter values returned by <c>croniq.TriggerDeadLetterInsert</c>.
/// </summary>
public readonly record struct TriggerDeadLetterInsertOutput(
    long? DeadLetterId,
    DateTime? CreatedUtc
);

public sealed class TriggerDeadLetterInsertResult
{
	/// <summary>
	/// Indicates whether the procedure executed without raising an error.
	/// </summary>
	public bool Success { get; init; }
	/// <summary>
	/// Contains the error message when <see cref="Success"/> is <c>false</c>; otherwise <c>null</c>.
	/// </summary>
	public string? Error { get; init; }
	/// <summary>
	/// OUTPUT parameter payload returned by the procedure.
	/// </summary>
	public TriggerDeadLetterInsertOutput? Output { get; init; }
}

internal static class TriggerDeadLetterInsertRequestMapper
{
    public static async ValueTask<TriggerDeadLetterInsertInput> ToInputAsync(TriggerDeadLetterInsertRequest? request, IXtraqParameterBindingProvider? bindingProvider, CancellationToken cancellationToken = default)
    {
        request ??= new TriggerDeadLetterInsertRequest();
        IReadOnlyList<ActorRef>? Actor = default;
        if (!HasValue(Actor))
        {
            Actor = await ResolveTableAsync<ActorRef>(bindingProvider, "[croniq].[TriggerDeadLetterInsert]", "@Actor", Actor, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(Actor))
        {
            throw new InvalidOperationException("Parameter @Actor must be supplied by the request or a configured binding.");
        }
        IReadOnlyList<TriggerDeadLetterRef>? DeadLetter = TriggerDeadLetterRefRequest.ToTableTypes(request.DeadLetter);
        if (!HasValue(DeadLetter))
        {
            DeadLetter = await ResolveTableAsync<TriggerDeadLetterRef>(bindingProvider, "[croniq].[TriggerDeadLetterInsert]", "@DeadLetter", DeadLetter, cancellationToken).ConfigureAwait(false);
        }
        if (!HasValue(DeadLetter))
        {
            throw new InvalidOperationException("Parameter @DeadLetter must be supplied by the request or a configured binding.");
        }

        return new TriggerDeadLetterInsertInput(
            Actor!,
            DeadLetter!
        );
    }

    public static ValueTask<TriggerDeadLetterInsertInput> ToInputAsync(TriggerDeadLetterInsertRequest? request, IXtraqDbContext dbContext, CancellationToken cancellationToken = default)
    {
        return ToInputAsync(request, dbContext as IXtraqParameterBindingProvider, cancellationToken);
    }

    private static bool HasValue<T>(T? value) => value is not null;

    private static async ValueTask<T?> ResolveAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, bool isTableType, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, isTableType, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        return ConvertValue<T>(resolved);
    }

    private static async ValueTask<IReadOnlyList<T>?> ResolveTableAsync<T>(IXtraqParameterBindingProvider? bindingProvider, string procedureFullName, string parameterName, object? currentValue, CancellationToken cancellationToken)
    {
        var resolved = await ParameterBindingEngine.ResolveValueAsync(procedureFullName, parameterName, true, currentValue, bindingProvider, cancellationToken).ConfigureAwait(false);
        if (resolved is null) return null;
        if (resolved is IReadOnlyList<T> roList) return roList;
        if (resolved is IEnumerable<T> enumerable) return enumerable as IReadOnlyList<T> ?? enumerable.ToArray();
        return null;
    }

    private static T? ConvertValue<T>(object? value)
    {
        if (value is null or DBNull) return default;
        if (value is T typed) return typed;
        try
        {
            return (T?)System.Convert.ChangeType(value, typeof(T), System.Globalization.CultureInfo.InvariantCulture);
        }
        catch
        {
            return default;
        }
    }
}

internal static partial class TriggerDeadLetterInsertPlan
{
	private static ProcedureExecutionPlan? _cached;
	public static ProcedureExecutionPlan Instance => _cached ??= Create();
	private static ProcedureExecutionPlan Create()
	{
		var parameters = new ProcedureParameter[]
		{
            new("@Actor", System.Data.DbType.Object, null, false, false, "core.ActorRef"),
            new("@DeadLetter", System.Data.DbType.Object, null, false, false, "croniq.TriggerDeadLetterRef"),
            new("@DeadLetterId", System.Data.DbType.Int64, 8, true, true),
            new("@CreatedUtc", System.Data.DbType.DateTime2, 7, true, true),
        };

		var resultSets = Array.Empty<ResultSetMapping>();

		object? OutputFactory(IReadOnlyDictionary<string, object?> values) => new TriggerDeadLetterInsertOutput(values.TryGetValue("DeadLetterId", out var v_DeadLetterId) ? (long?)v_DeadLetterId : default, values.TryGetValue("CreatedUtc", out var v_CreatedUtc) ? (DateTime?)v_CreatedUtc : default);
		object AggregateFactory(bool success, string? error, object? output, IReadOnlyDictionary<string, object?> outputs, object[] rs)
		{
			return new TriggerDeadLetterInsertResult
			{
				Success = success,
				Error = error,
				Output = (TriggerDeadLetterInsertOutput?)output
			};
		}
		void Binder(DbCommand cmd, object? state)
		{
			var input = (TriggerDeadLetterInsertInput)state!;
			{ var prm = cmd.Parameters["@Actor"]; var source = input.Actor; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "core.ActorRef"; } }
			{ var prm = cmd.Parameters["@DeadLetter"]; var source = input.DeadLetter; var tvp = TvpHelper.BuildRecords(source) ?? Array.Empty<Microsoft.Data.SqlClient.Server.SqlDataRecord>(); prm.Value = tvp; if (prm is Microsoft.Data.SqlClient.SqlParameter sp) { sp.SqlDbType = System.Data.SqlDbType.Structured; sp.TypeName ??= "croniq.TriggerDeadLetterRef"; } }
		}
		return new ProcedureExecutionPlan(
			"[croniq].[TriggerDeadLetterInsert]", parameters, resultSets, OutputFactory, AggregateFactory, Binder);
	}
}

/// <summary>Convenience extension for executing '[croniq].[TriggerDeadLetterInsert]' via an <see cref="IXtraqDbContext"/>.</summary>
public static class TriggerDeadLetterInsertExtensions
{
	public static async Task<TriggerDeadLetterInsertResult> TriggerDeadLetterInsertAsync(this IXtraqDbContext db, TriggerDeadLetterInsertRequest request, CancellationToken cancellationToken = default)
	{
		var bindingProvider = db as IXtraqParameterBindingProvider;
		var input = await TriggerDeadLetterInsertRequestMapper.ToInputAsync(request, bindingProvider, cancellationToken).ConfigureAwait(false);
		return await TriggerDeadLetterInsertAsync(db, input, cancellationToken).ConfigureAwait(false);
	}

	public static async Task<TriggerDeadLetterInsertResult> TriggerDeadLetterInsertAsync(this IXtraqDbContext db, TriggerDeadLetterInsertInput input, CancellationToken cancellationToken = default)
	{
		await using var conn = await db.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
		return await TriggerDeadLetterInsertProcedure.ExecuteAsync(db as IXtraqProcedureInterceptorProvider, db as IXtraqParameterBindingProvider, conn, input, cancellationToken).ConfigureAwait(false);
	}

}

/// <summary>Low-level execution wrapper for a single stored procedure invocation.</summary>
public static class TriggerDeadLetterInsertProcedure
{
	public const string Name = "[croniq].[TriggerDeadLetterInsert]";
	public static Task<TriggerDeadLetterInsertResult> ExecuteAsync(DbConnection connection, TriggerDeadLetterInsertInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(null, null, connection, input, cancellationToken);

	public static Task<TriggerDeadLetterInsertResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, DbConnection connection, TriggerDeadLetterInsertInput input, CancellationToken cancellationToken = default)
		=> ExecuteAsync(interceptorProvider, null, connection, input, cancellationToken);

	public static Task<TriggerDeadLetterInsertResult> ExecuteAsync(IXtraqProcedureInterceptorProvider? interceptorProvider, IXtraqParameterBindingProvider? bindingProvider, DbConnection connection, TriggerDeadLetterInsertInput input, CancellationToken cancellationToken = default)
	{
		return ProcedureExecutor.ExecuteAsync<TriggerDeadLetterInsertResult>(interceptorProvider, bindingProvider, connection, TriggerDeadLetterInsertPlan.Instance, input, cancellationToken);
	}

}
