// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.TriggerLeaseReleaseRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record TriggerLeaseReleaseRef : ITableType
{
    public long LeaseId { get; init; }
    public string InstanceId { get; init; } = string.Empty;
    public bool Succeeded { get; init; }
    public DateTime? NextFireAtUtc { get; init; }
    public string? DeadLetterReason { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public TriggerLeaseReleaseRef() { }

	public static TriggerLeaseReleaseRef Create(
        long LeaseId,
        string InstanceId,
        bool Succeeded,
        DateTime? NextFireAtUtc,
        string? DeadLetterReason
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new TriggerLeaseReleaseRef
    {
        LeaseId = LeaseId,
        InstanceId = InstanceId,
        Succeeded = Succeeded,
        NextFireAtUtc = NextFireAtUtc,
        DeadLetterReason = DeadLetterReason
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class TriggerLeaseReleaseRefBuilder
	{
        private long _LeaseId;
        private string _InstanceId = string.Empty;
        private bool _Succeeded;
        private DateTime? _NextFireAtUtc;
        private string? _DeadLetterReason;
        public TriggerLeaseReleaseRefBuilder WithLeaseId(long value) { _LeaseId = value; return this; }
        public TriggerLeaseReleaseRefBuilder WithInstanceId(string value) { _InstanceId = value; return this; }
        public TriggerLeaseReleaseRefBuilder WithSucceeded(bool value) { _Succeeded = value; return this; }
        public TriggerLeaseReleaseRefBuilder WithNextFireAtUtc(DateTime? value) { _NextFireAtUtc = value; return this; }
        public TriggerLeaseReleaseRefBuilder WithDeadLetterReason(string? value) { _DeadLetterReason = value; return this; }
        public TriggerLeaseReleaseRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new TriggerLeaseReleaseRef
            {
                LeaseId = _LeaseId,
                InstanceId = _InstanceId,
                Succeeded = _Succeeded,
                NextFireAtUtc = _NextFireAtUtc,
                DeadLetterReason = _DeadLetterReason
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// HTTP request row mirroring the SQL table type <c>Croniq.TriggerLeaseReleaseRef</c> with DataAnnotations metadata.
/// </summary>
public sealed record TriggerLeaseReleaseRefRequest
{
    public long LeaseId { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string InstanceId { get; init; } = string.Empty;
    public bool Succeeded { get; init; }
    public DateTime? NextFireAtUtc { get; init; }
    [System.ComponentModel.DataAnnotations.StringLength(128)]
    public string? DeadLetterReason { get; init; }

	internal TriggerLeaseReleaseRef ToTableType()
		=> TriggerLeaseReleaseRef.Create(
            LeaseId,
            InstanceId,
            Succeeded,
            NextFireAtUtc,
            DeadLetterReason
        );

	internal static System.Collections.Generic.IReadOnlyList<TriggerLeaseReleaseRef>? ToTableTypes(System.Collections.Generic.IReadOnlyList<TriggerLeaseReleaseRefRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<TriggerLeaseReleaseRef>();
		var buffer = new TriggerLeaseReleaseRef[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
