// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.InstanceRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record InstanceRef : ITableType
{
    public string InstanceId { get; init; } = string.Empty;
    public string Environment { get; init; } = string.Empty;
    public string NodeName { get; init; } = string.Empty;
    public string? Capabilities { get; init; }
    public string Version { get; init; } = string.Empty;

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public InstanceRef() { }

	public static InstanceRef Create(
        string InstanceId,
        string Environment,
        string NodeName,
        string? Capabilities,
        string Version
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new InstanceRef
    {
        InstanceId = InstanceId,
        Environment = Environment,
        NodeName = NodeName,
        Capabilities = Capabilities,
        Version = Version
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class InstanceRefBuilder
	{
        private string _InstanceId = string.Empty;
        private string _Environment = string.Empty;
        private string _NodeName = string.Empty;
        private string? _Capabilities;
        private string _Version = string.Empty;
        public InstanceRefBuilder WithInstanceId(string value) { _InstanceId = value; return this; }
        public InstanceRefBuilder WithEnvironment(string value) { _Environment = value; return this; }
        public InstanceRefBuilder WithNodeName(string value) { _NodeName = value; return this; }
        public InstanceRefBuilder WithCapabilities(string? value) { _Capabilities = value; return this; }
        public InstanceRefBuilder WithVersion(string value) { _Version = value; return this; }
        public InstanceRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new InstanceRef
            {
                InstanceId = _InstanceId,
                Environment = _Environment,
                NodeName = _NodeName,
                Capabilities = _Capabilities,
                Version = _Version
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// HTTP request row mirroring the SQL table type <c>Croniq.InstanceRef</c> with DataAnnotations metadata.
/// </summary>
public sealed record InstanceRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string InstanceId { get; init; } = string.Empty;
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(32)]
    public string Environment { get; init; } = string.Empty;
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string NodeName { get; init; } = string.Empty;
    public string? Capabilities { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string Version { get; init; } = string.Empty;

	internal InstanceRef ToTableType()
		=> InstanceRef.Create(
            InstanceId,
            Environment,
            NodeName,
            Capabilities,
            Version
        );

	internal static System.Collections.Generic.IReadOnlyList<InstanceRef>? ToTableTypes(System.Collections.Generic.IReadOnlyList<InstanceRefRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<InstanceRef>();
		var buffer = new InstanceRef[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
