// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Croniq;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Croniq.JobRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record JobRef : ITableType
{
    public string JobKey { get; init; } = string.Empty;
    public int TenantId { get; init; }
    public string Environment { get; init; } = string.Empty;
    public string Namespace { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string? Variant { get; init; }
    public string? Description { get; init; }
    public string? Metadata { get; init; }

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public JobRef() { }

	public static JobRef Create(
        string JobKey,
        int TenantId,
        string Environment,
        string Namespace,
        string Name,
        string? Variant,
        string? Description,
        string? Metadata
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new JobRef
    {
        JobKey = JobKey,
        TenantId = TenantId,
        Environment = Environment,
        Namespace = Namespace,
        Name = Name,
        Variant = Variant,
        Description = Description,
        Metadata = Metadata
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class JobRefBuilder
	{
        private string _JobKey = string.Empty;
        private int _TenantId;
        private string _Environment = string.Empty;
        private string _Namespace = string.Empty;
        private string _Name = string.Empty;
        private string? _Variant;
        private string? _Description;
        private string? _Metadata;
        public JobRefBuilder WithJobKey(string value) { _JobKey = value; return this; }
        public JobRefBuilder WithTenantId(int value) { _TenantId = value; return this; }
        public JobRefBuilder WithEnvironment(string value) { _Environment = value; return this; }
        public JobRefBuilder WithNamespace(string value) { _Namespace = value; return this; }
        public JobRefBuilder WithName(string value) { _Name = value; return this; }
        public JobRefBuilder WithVariant(string? value) { _Variant = value; return this; }
        public JobRefBuilder WithDescription(string? value) { _Description = value; return this; }
        public JobRefBuilder WithMetadata(string? value) { _Metadata = value; return this; }
        public JobRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new JobRef
            {
                JobKey = _JobKey,
                TenantId = _TenantId,
                Environment = _Environment,
                Namespace = _Namespace,
                Name = _Name,
                Variant = _Variant,
                Description = _Description,
                Metadata = _Metadata
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// HTTP request row mirroring the SQL table type <c>Croniq.JobRef</c> with DataAnnotations metadata.
/// </summary>
public sealed record JobRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string JobKey { get; init; } = string.Empty;
    public int TenantId { get; init; }
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(32)]
    public string Environment { get; init; } = string.Empty;
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string Namespace { get; init; } = string.Empty;
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(128)]
    public string Name { get; init; } = string.Empty;
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string? Variant { get; init; }
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string? Description { get; init; }
    public string? Metadata { get; init; }

	internal JobRef ToTableType()
		=> JobRef.Create(
            JobKey,
            TenantId,
            Environment,
            Namespace,
            Name,
            Variant,
            Description,
            Metadata
        );

	internal static System.Collections.Generic.IReadOnlyList<JobRef>? ToTableTypes(System.Collections.Generic.IReadOnlyList<JobRefRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<JobRef>();
		var buffer = new JobRef[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
