<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Croniq.Core\Croniq.Core.csproj" />
    <ProjectReference Include="..\Croniq.JobStore.InMemory\Croniq.JobStore.InMemory.csproj" />
    <ProjectReference Include="..\Croniq.Providers.Default\Croniq.Providers.Default.csproj" />
    <ProjectReference Include="..\Croniq.Providers.Abstractions\Croniq.Providers.Abstractions.csproj" />
    <ProjectReference Include="..\Croniq.Persistence.Abstractions\Croniq.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\Croniq.Persistence.SqlServer\Croniq.Persistence.SqlServer.csproj" />
    <ProjectReference Include="..\Croniq.Auth.Abstractions\Croniq.Auth.Abstractions.csproj" />
    <ProjectReference Include="..\Croniq.Auth.Core\Croniq.Auth.Core.csproj" />
    <ProjectReference Include="..\Croniq.Auth.SqlServer\Croniq.Auth.SqlServer.csproj" />
    <ProjectReference Include="..\Croniq.Data.SqlServer\Croniq.Data.SqlServer.csproj" />
    <ProjectReference Include="..\Croniq.Hosting\Croniq.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.4" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
    <PackageReference Include="Grpc.AspNetCore.Server" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="..\Croniq.Rpc.Client\Protos\scheduler.proto" GrpcServices="Both" Link="Protos\scheduler.proto" />
  </ItemGroup>
</Project>
