<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Croniq.Data.Postgres\Croniq.Data.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Data.SqlServer\Croniq.Data.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Auth.Abstractions\Croniq.Auth.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Auth.Postgres\Croniq.Auth.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Croniq.Auth.SqlServer\Croniq.Auth.SqlServer.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>