<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Croniq.Auth.Abstractions\Croniq.Auth.Abstractions.csproj" />
    <ProjectReference Include="..\Croniq.Auth.Core\Croniq.Auth.Core.csproj" />
    <ProjectReference Include="..\Croniq.Core\Croniq.Core.csproj" />
    <ProjectReference Include="..\Croniq.Data.SqlServer\Croniq.Data.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>
</Project>