//! `croniq migrate` — convert a crontab file to a Croniqfile.

use std::path::Path;

use miette::{Result, miette};

pub fn migrate(crontab_path: &Path, output: Option<&Path>) -> Result<()> {
    let content = std::fs::read_to_string(crontab_path)
        .map_err(|e| miette!("Failed to read {}: {e}", crontab_path.display()))?;

    let mut jobs = Vec::new();
    let mut job_index = 0;

    for line in content.lines() {
        let line = line.trim();
        // Skip empty lines, comments, and variable assignments
        if line.is_empty() || line.starts_with('#') || line.contains('=') && !line.contains(' ') {
            continue;
        }

        // Try to parse as cron entry: 5 fields + command
        let parts: Vec<&str> = line.splitn(6, char::is_whitespace).collect();
        if parts.len() < 6 {
            continue;
        }

        let cron_expr = format!("{} {} {} {} {}", parts[0], parts[1], parts[2], parts[3], parts[4]);
        let command = parts[5].trim();

        job_index += 1;

        // Generate a job key from the command
        let job_key = derive_job_key(command, job_index);

        // Convert cron to DSL using the convert module
        let dsl_schedule = match croniq_config::convert::convert(&cron_expr) {
            Ok(result) => result.schedule,
            Err(_) => format!("# Could not convert: {cron_expr}\n  every day at 00:00"),
        };

        jobs.push(format!(
            r#"job {job_key} {{
  {dsl_schedule}
  timeout 5m
  metadata {{ original_command "{command}" }}
}}"#
        ));
    }

    if jobs.is_empty() {
        return Err(miette!("No cron entries found in {}", crontab_path.display()));
    }

    let croniqfile = format!(
        r#"# Croniqfile — migrated from {}
# Generated by: croniq migrate
# Review and adjust job keys, timeouts, and runner requirements.

server {{
  listen :4000
  data_dir .data
}}

defaults {{
  timeout 5m
  retry exponential {{ max_attempts 3; base 2s; cap 30s }}
}}

{}
"#,
        crontab_path.display(),
        jobs.join("\n\n")
    );

    match output {
        Some(path) => {
            std::fs::write(path, &croniqfile)
                .map_err(|e| miette!("Failed to write {}: {e}", path.display()))?;
            println!("Migrated {} cron entries → {}", jobs.len(), path.display());
        }
        None => {
            print!("{croniqfile}");
        }
    }

    Ok(())
}

fn derive_job_key(command: &str, index: usize) -> String {
    // Try to extract a meaningful name from the command
    let cmd = command
        .split('|').next().unwrap_or(command)
        .split('>').next().unwrap_or(command)
        .trim();

    // Get the base command name
    let base = cmd
        .split_whitespace()
        .next()
        .unwrap_or("task")
        .rsplit('/')
        .next()
        .unwrap_or("task");

    // Clean up
    let clean: String = base
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-' || *c == '_')
        .collect();

    let name = if clean.is_empty() { "task".to_string() } else { clean };

    format!("migrated:{name}-{index}")
}
