// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Core;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Core.ActorRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record ActorRef : ITableType
{
    public string Actor { get; init; } = string.Empty;

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public ActorRef() { }

	public static ActorRef Create(
        string Actor
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new ActorRef
    {
        Actor = Actor
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class ActorRefBuilder
	{
        private string _Actor = string.Empty;
        public ActorRefBuilder WithActor(string value) { _Actor = value; return this; }
        public ActorRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new ActorRef
            {
                Actor = _Actor
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

