// <auto-generated/>
// Xtraq Code Generator. Do not edit this file directly.
// Changes may be overwritten. For customization extend generated partials.

#nullable enable
using System;

namespace Croniq.Persistence.Xtraq.Core;

/// <summary>
/// Provides a strongly typed projection over the SQL table type <c>Core.ActorRef</c>.
/// </summary>
/// <remarks>
/// Generated by the Xtraq CLI at <generated>. Modify the originating SQL table type to change this artifact.
/// </remarks>
public sealed record ActorRef : ITableType
{
    public string Actor { get; init; } = string.Empty;

	[Obsolete("Use the static Create(...) or builder for construction.")]
	public ActorRef() { }

	public static ActorRef Create(
        string Actor
    ) =>
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in factory
    new ActorRef
    {
        Actor = Actor
    };
#pragma warning restore CS0612, CS0618

#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage warnings for internal factory construction

	public sealed class ActorRefBuilder
	{
        private string _Actor = string.Empty;
        public ActorRefBuilder WithActor(string value) { _Actor = value; return this; }
        public ActorRef Build()
        {
#pragma warning disable CS0612, CS0618 // Suppress obsolete ctor usage in builder
            var result = new ActorRef
            {
                Actor = _Actor
            };
#pragma warning restore CS0612, CS0618
            return result;
        }
	}
#pragma warning restore CS0612, CS0618
}

/// <summary>
/// HTTP request row mirroring the SQL table type <c>Core.ActorRef</c> with DataAnnotations metadata.
/// </summary>
public sealed record ActorRefRequest
{
    [System.ComponentModel.DataAnnotations.Required]
    [System.ComponentModel.DataAnnotations.StringLength(128)]
    public string Actor { get; init; } = string.Empty;

	internal ActorRef ToTableType()
		=> ActorRef.Create(
            Actor
        );

	internal static System.Collections.Generic.IReadOnlyList<ActorRef>? ToTableTypes(System.Collections.Generic.IReadOnlyList<ActorRefRequest>? source)
	{
		if (source is null) return null;
		if (source.Count == 0) return System.Array.Empty<ActorRef>();
		var buffer = new ActorRef[source.Count];
		for (var i = 0; i < source.Count; i++)
		{
			var row = source[i];
			if (row is null)
			{
				throw new System.InvalidOperationException("Table type rows cannot contain null entries.");
			}

			buffer[i] = row.ToTableType();
		}

		return buffer;
	}
}
