import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/lib/wasm/` is generated by `scripts/build-wasm.sh` from the
  // croniq-config-wasm crate. Don't lint the bindgen output — its
  // `eslint-disable` directives are tuned for stricter configs and our
  // local plugin set produces "unused directive" warnings.
  globalIgnores(['dist', 'src/lib/wasm/']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
])
